#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("rangr.droid.Resource", IsApplication=true)]

namespace rangr.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::rangr.droid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::rangr.droid.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
			global::ModernHttpClient.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
			global::SQLite.Resource.String.ApplicationName = global::rangr.droid.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::rangr.droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int enter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int exit = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int post_detail_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int post_detail_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adUnitId = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int cameraBearing = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTargetLat = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLng = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTilt = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraZoom = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int mapType = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int uiCompass = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiRotateGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiScrollGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiTiltGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomControls = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int useViewLifecycle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int zOrderOnTop = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int common_signin_btn_text_dark = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int common_signin_btn_text_light = 2131099671;
			
			// aapt resource value: 0x7f06000b
			public const int feed_bg = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int feed_item_bg = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int feed_item_border = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int link = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int timestamp = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int white = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int xam_blue = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int xam_dark_blue = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int xam_gray = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int xam_green = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int xam_light_gray = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int xam_purple = 2131099664;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int activity_horizontal_margin = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int activity_vertical_margin = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int feed_item_border_width = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int feed_item_corner_radius = 2131296267;
			
			// aapt resource value: 0x7f090002
			public const int feed_item_margin = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int feed_item_padding_left_right = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int feed_item_padding_top_bottom = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int feed_item_profile_info_padd = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int feed_item_profile_name = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int feed_item_profile_pic = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int feed_item_status_pad_left_right = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int feed_item_status_pad_top = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int feed_item_timestamp = 2131296264;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_parent_rounded_corner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_error = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_help = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_refresh = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_medium_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_small_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_standard_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_plusone_tall_off_client = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Icon2x = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Placeholder = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int questionmark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int twitter = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int user_default_avatar = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0015
			public const int PostTextLabel = 2131492885;
			
			// aapt resource value: 0x7f0c0014
			public const int UserNameText = 2131492884;
			
			// aapt resource value: 0x7f0c0011
			public const int content_area = 2131492881;
			
			// aapt resource value: 0x7f0c000a
			public const int dialogImage = 2131492874;
			
			// aapt resource value: 0x7f0c0009
			public const int dialogLayout = 2131492873;
			
			// aapt resource value: 0x7f0c000b
			public const int dialogTitle = 2131492875;
			
			// aapt resource value: 0x7f0c001c
			public const int feedImage1 = 2131492892;
			
			// aapt resource value: 0x7f0c0016
			public const int fragmentContainer = 2131492886;
			
			// aapt resource value: 0x7f0c0000
			public const int hybrid = 2131492864;
			
			// aapt resource value: 0x7f0c0005
			public const int imageView1 = 2131492869;
			
			// aapt resource value: 0x7f0c0012
			public const int linearLayout1 = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int linearLayout2 = 2131492883;
			
			// aapt resource value: 0x7f0c001e
			public const int list = 2131492894;
			
			// aapt resource value: 0x7f0c0007
			public const int loadMoreButton = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int loadMoreProgress = 2131492872;
			
			// aapt resource value: 0x7f0c000e
			public const int logIn = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int loginProgress = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int loginQuestion = 2131492880;
			
			// aapt resource value: 0x7f0c0006
			public const int map = 2131492870;
			
			// aapt resource value: 0x7f0c0018
			public const int name = 2131492888;
			
			// aapt resource value: 0x7f0c0001
			public const int none = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int normal = 2131492866;
			
			// aapt resource value: 0x7f0c000d
			public const int password = 2131492877;
			
			// aapt resource value: 0x7f0c0017
			public const int profilePic = 2131492887;
			
			// aapt resource value: 0x7f0c001d
			public const int refresher = 2131492893;
			
			// aapt resource value: 0x7f0c0003
			public const int satellite = 2131492867;
			
			// aapt resource value: 0x7f0c001f
			public const int settings_menu_item = 2131492895;
			
			// aapt resource value: 0x7f0c0004
			public const int terrain = 2131492868;
			
			// aapt resource value: 0x7f0c0019
			public const int timestamp = 2131492889;
			
			// aapt resource value: 0x7f0c001a
			public const int txtStatusMsg = 2131492890;
			
			// aapt resource value: 0x7f0c001b
			public const int txtUrl = 2131492891;
			
			// aapt resource value: 0x7f0c000c
			public const int userName = 2131492876;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int empty = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int google_map = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int post_detail = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int post_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int posts = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int main = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001b
			public const int ApplicationName = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int Hello = 2131165210;
			
			// aapt resource value: 0x7f070020
			public const int action_login = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int action_settings = 2131165217;
			
			// aapt resource value: 0x7f07001d
			public const int app_name = 2131165213;
			
			// aapt resource value: 0x7f070015
			public const int auth_client_needs_enabling_title = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int auth_client_needs_installation_title = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int auth_client_needs_update_title = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int auth_client_play_services_err_notification_msg = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int auth_client_requested_by_msg = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int auth_client_using_bad_version_title = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_enable_button = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_enable_text = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_enable_title = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_install_text_phone = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_install_text_tablet = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_install_title = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_invalid_account_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_invalid_account_title = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_network_error_text = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_network_error_title = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_unknown_issue = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unsupported_date_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_unsupported_text = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_unsupported_title = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_update_button = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_update_title = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int common_signin_button_text = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int common_signin_button_text_long = 2131165203;
			
			// aapt resource value: 0x7f07001f
			public const int hint_login_password = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int hint_login_username = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int library_name = 2131165212;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppBaseTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int AppTheme = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int CodeFont = 2131361794;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int preferences_general = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adUnitId = 1;
			
			public static int[] MapAttrs = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
