#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("rangr.droid.Resource", IsApplication=true)]

namespace rangr.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::rangr.droid.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::rangr.droid.Resource.String.Hello;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::rangr.droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::rangr.droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::rangr.droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::rangr.droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::rangr.droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::rangr.droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::rangr.droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::rangr.droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::rangr.droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::rangr.droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::rangr.droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::rangr.droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::rangr.droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::rangr.droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::rangr.droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::rangr.droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::rangr.droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::rangr.droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::rangr.droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::rangr.droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::rangr.droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::rangr.droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::rangr.droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::rangr.droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::rangr.droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::rangr.droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::rangr.droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::rangr.droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::rangr.droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::rangr.droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::rangr.droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::rangr.droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::rangr.droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::rangr.droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::rangr.droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::rangr.droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Splat.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
			global::ModernHttpClient.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
			global::droid_ui_lib.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
			global::droid_common_lib.Resource.String.library_name = global::rangr.droid.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int enter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int exit = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int post_detail_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int post_detail_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int navigation_drawer_list = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adUnitId = 2130771969;
			
			// aapt resource value: 0x7f010013
			public const int ahBarColor = 2130771987;
			
			// aapt resource value: 0x7f01001b
			public const int ahBarLength = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int ahBarWidth = 2130771994;
			
			// aapt resource value: 0x7f010018
			public const int ahCircleColor = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int ahDelayMillis = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int ahRadius = 2130771993;
			
			// aapt resource value: 0x7f010014
			public const int ahRimColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int ahRimWidth = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int ahSpinSpeed = 2130771990;
			
			// aapt resource value: 0x7f010010
			public const int ahText = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int ahTextColor = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int ahTextSize = 2130771986;
			
			// aapt resource value: 0x7f010003
			public const int cameraBearing = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTargetLat = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLng = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTilt = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraZoom = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int mapType = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int uiCompass = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiRotateGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiScrollGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiTiltGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomControls = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int useViewLifecycle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int zOrderOnTop = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int common_signin_btn_text_dark = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int common_signin_btn_text_light = 2131099671;
			
			// aapt resource value: 0x7f06000b
			public const int feed_bg = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int feed_item_bg = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int feed_item_border = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int link = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int timestamp = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int white = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int xam_blue = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int xam_dark_blue = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int xam_gray = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int xam_green = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int xam_light_gray = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int xam_purple = 2131099664;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f09000d
			public const int action_bar_default_height = 2131296269;
			
			// aapt resource value: 0x7f090011
			public const int action_bar_subtitle_bottom_margin = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int action_bar_subtitle_text_size = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int action_bar_subtitle_top_margin = 2131296272;
			
			// aapt resource value: 0x7f09000e
			public const int action_bar_title_text_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int activity_horizontal_margin = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int activity_vertical_margin = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int feed_item_border_width = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int feed_item_corner_radius = 2131296267;
			
			// aapt resource value: 0x7f090002
			public const int feed_item_margin = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int feed_item_padding_left_right = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int feed_item_padding_top_bottom = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int feed_item_profile_info_padd = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int feed_item_profile_name = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int feed_item_profile_pic = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int feed_item_status_pad_left_right = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int feed_item_status_pad_top = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int feed_item_timestamp = 2131296264;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_parent_rounded_corner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int drawer_shadow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_error = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_help = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_location_found = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_new = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_action_refresh = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_send_now = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_drawer = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_errorstatus = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_launcher = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_plusone_medium_off_client = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_plusone_small_off_client = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_plusone_standard_off_client = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_plusone_tall_off_client = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_successstatus = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Icon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Icon2x = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Placeholder = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int questionmark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int roundedbg = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int roundedbgdark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int twitter = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int user_default_avatar = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d002d
			public const int Divider = 2131558445;
			
			// aapt resource value: 0x7f0d000e
			public const int EmailButton = 2131558414;
			
			// aapt resource value: 0x7f0d0011
			public const int HeaderTextView = 2131558417;
			
			// aapt resource value: 0x7f0d000d
			public const int NameTextView = 2131558413;
			
			// aapt resource value: 0x7f0d002e
			public const int PhoneButton = 2131558446;
			
			// aapt resource value: 0x7f0d0026
			public const int PostText = 2131558438;
			
			// aapt resource value: 0x7f0d002f
			public const int PostTextLabel = 2131558447;
			
			// aapt resource value: 0x7f0d0038
			public const int ProfileList = 2131558456;
			
			// aapt resource value: 0x7f0d0028
			public const int SwipeContent = 2131558440;
			
			// aapt resource value: 0x7f0d0025
			public const int UserNameText = 2131558437;
			
			// aapt resource value: 0x7f0d000c
			public const int ValueTextView = 2131558412;
			
			// aapt resource value: 0x7f0d0006
			public const int action_bar_subtitle = 2131558406;
			
			// aapt resource value: 0x7f0d0005
			public const int action_bar_title = 2131558405;
			
			// aapt resource value: 0x7f0d0023
			public const int content_frame = 2131558435;
			
			// aapt resource value: 0x7f0d001a
			public const int dialogImage = 2131558426;
			
			// aapt resource value: 0x7f0d0019
			public const int dialogLayout = 2131558425;
			
			// aapt resource value: 0x7f0d001b
			public const int dialogTitle = 2131558427;
			
			// aapt resource value: 0x7f0d0008
			public const int displayName = 2131558408;
			
			// aapt resource value: 0x7f0d002b
			public const int distance = 2131558443;
			
			// aapt resource value: 0x7f0d0022
			public const int drawer_layout = 2131558434;
			
			// aapt resource value: 0x7f0d0037
			public const int feedImage1 = 2131558455;
			
			// aapt resource value: 0x7f0d0027
			public const int fragmentContainer = 2131558439;
			
			// aapt resource value: 0x7f0d0000
			public const int hybrid = 2131558400;
			
			// aapt resource value: 0x7f0d000f
			public const int imageView1 = 2131558415;
			
			// aapt resource value: 0x7f0d0024
			public const int left_drawer = 2131558436;
			
			// aapt resource value: 0x7f0d000a
			public const int linearLayout1 = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public const int linearLayout2 = 2131558411;
			
			// aapt resource value: 0x7f0d0029
			public const int linearLayout3 = 2131558441;
			
			// aapt resource value: 0x7f0d0031
			public const int list = 2131558449;
			
			// aapt resource value: 0x7f0d0017
			public const int loadMoreButton = 2131558423;
			
			// aapt resource value: 0x7f0d0018
			public const int loadMoreProgress = 2131558424;
			
			// aapt resource value: 0x7f0d0015
			public const int loadingImage = 2131558421;
			
			// aapt resource value: 0x7f0d0013
			public const int loadingProgressBar = 2131558419;
			
			// aapt resource value: 0x7f0d0016
			public const int loadingProgressWheel = 2131558422;
			
			// aapt resource value: 0x7f0d001e
			public const int logIn = 2131558430;
			
			// aapt resource value: 0x7f0d0020
			public const int loginProgress = 2131558432;
			
			// aapt resource value: 0x7f0d0021
			public const int loginQuestion = 2131558433;
			
			// aapt resource value: 0x7f0d0010
			public const int map = 2131558416;
			
			// aapt resource value: 0x7f0d0033
			public const int name = 2131558451;
			
			// aapt resource value: 0x7f0d003f
			public const int new_post_menu_item = 2131558463;
			
			// aapt resource value: 0x7f0d0001
			public const int none = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int normal = 2131558402;
			
			// aapt resource value: 0x7f0d001d
			public const int password = 2131558429;
			
			// aapt resource value: 0x7f0d002a
			public const int personName = 2131558442;
			
			// aapt resource value: 0x7f0d0032
			public const int profilePic = 2131558450;
			
			// aapt resource value: 0x7f0d003a
			public const int radio_A = 2131558458;
			
			// aapt resource value: 0x7f0d003b
			public const int radio_B = 2131558459;
			
			// aapt resource value: 0x7f0d003c
			public const int radio_C = 2131558460;
			
			// aapt resource value: 0x7f0d003d
			public const int radio_D = 2131558461;
			
			// aapt resource value: 0x7f0d0039
			public const int radio_Live = 2131558457;
			
			// aapt resource value: 0x7f0d0030
			public const int refresher = 2131558448;
			
			// aapt resource value: 0x7f0d0003
			public const int satellite = 2131558403;
			
			// aapt resource value: 0x7f0d0040
			public const int search_posts_menu_item = 2131558464;
			
			// aapt resource value: 0x7f0d003e
			public const int send_post_menu_item = 2131558462;
			
			// aapt resource value: 0x7f0d0007
			public const int spinner_title = 2131558407;
			
			// aapt resource value: 0x7f0d002c
			public const int status = 2131558444;
			
			// aapt resource value: 0x7f0d0009
			public const int statusMessage = 2131558409;
			
			// aapt resource value: 0x7f0d0004
			public const int terrain = 2131558404;
			
			// aapt resource value: 0x7f0d0014
			public const int textViewStatus = 2131558420;
			
			// aapt resource value: 0x7f0d0034
			public const int timestamp = 2131558452;
			
			// aapt resource value: 0x7f0d0035
			public const int txtStatusMsg = 2131558453;
			
			// aapt resource value: 0x7f0d0036
			public const int txtUrl = 2131558454;
			
			// aapt resource value: 0x7f0d001f
			public const int userMobile = 2131558431;
			
			// aapt resource value: 0x7f0d001c
			public const int userName = 2131558428;
			
			// aapt resource value: 0x7f0d0012
			public const int view1 = 2131558418;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar_spinner = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int action_bar_spinner_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditProfile = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmailPropertyListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int empty = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GoogleMap = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GroupHeaderListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loading = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int loadingprogress = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int loadingProgressBar = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int loadMore = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int login = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int main_drawer_list_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int main_with_drawer = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int new_post = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int People = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PeopleList = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PeopleListItem = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PhonePropertyListItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int post_detail = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int post_list = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int post_list_item = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Profile = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int PropertyListItem = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int simulation = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int TwitterPropertyListItem = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int UrlPropertyListItem = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int main = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int new_post = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int posts = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int search = 2131492867;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001c
			public const int ApplicationName = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int Hello = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int action_login = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int action_new_post = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int action_search_posts = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int action_send_post = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int action_settings = 2131165217;
			
			// aapt resource value: 0x7f07001d
			public const int app_name = 2131165213;
			
			// aapt resource value: 0x7f070027
			public const int app_not_available = 2131165223;
			
			// aapt resource value: 0x7f070015
			public const int auth_client_needs_enabling_title = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int auth_client_needs_installation_title = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int auth_client_needs_update_title = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int auth_client_play_services_err_notification_msg = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int auth_client_requested_by_msg = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int auth_client_using_bad_version_title = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_enable_button = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_enable_text = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_enable_title = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_install_text_phone = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_install_text_tablet = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_install_title = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_invalid_account_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_invalid_account_title = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_network_error_text = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_network_error_title = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_unknown_issue = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unsupported_date_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_unsupported_text = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_unsupported_title = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_update_button = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_update_title = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int common_signin_button_text = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int common_signin_button_text_long = 2131165203;
			
			// aapt resource value: 0x7f070026
			public const int drawer_close = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int drawer_open = 2131165221;
			
			// aapt resource value: 0x7f07001f
			public const int hint_login_password = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int hint_login_usermobile = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int library_name = 2131165210;
			
			// aapt resource value: 0x7f07002a
			public const int new_post_title = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int posts_title = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int search_title = 2131165225;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int AppBaseTheme = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int AppTheme = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int CodeFont = 2131427330;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int preferences_general = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adUnitId = 1;
			
			public static int[] MapAttrs = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
