#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("App.Android.Resource", IsApplication=true)]

namespace App.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int feed_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int feed_item_bg = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int feed_item_border = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int link = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int timestamp = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int xam_blue = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int xam_dark_blue = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int xam_gray = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int xam_green = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int xam_light_gray = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int xam_purple = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int feed_item_border_width = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int feed_item_corner_radius = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int feed_item_margin = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int feed_item_padding_left_right = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int feed_item_padding_top_bottom = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int feed_item_profile_info_padd = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int feed_item_profile_name = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int feed_item_profile_pic = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int feed_item_status_pad_left_right = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int feed_item_status_pad_top = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int feed_item_timestamp = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_parent_rounded_corner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int empty_basket = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon2x = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Placeholder = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int questionmark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int twitter = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int user_default_avatar = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001c
			public const int Divider = 2131296284;
			
			// aapt resource value: 0x7f090006
			public const int EmailButton = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int HeaderTextView = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int NameTextView = 2131296261;
			
			// aapt resource value: 0x7f09001d
			public const int PhoneButton = 2131296285;
			
			// aapt resource value: 0x7f090014
			public const int PostText = 2131296276;
			
			// aapt resource value: 0x7f09001e
			public const int PostTextLabel = 2131296286;
			
			// aapt resource value: 0x7f090027
			public const int ProfileList = 2131296295;
			
			// aapt resource value: 0x7f090017
			public const int SwipeContent = 2131296279;
			
			// aapt resource value: 0x7f090013
			public const int UserNameText = 2131296275;
			
			// aapt resource value: 0x7f090004
			public const int ValueTextView = 2131296260;
			
			// aapt resource value: 0x7f09002b
			public const int action_settings = 2131296299;
			
			// aapt resource value: 0x7f09000c
			public const int dialogImage = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int dialogLayout = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int dialogTitle = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int displayName = 2131296256;
			
			// aapt resource value: 0x7f09001a
			public const int distance = 2131296282;
			
			// aapt resource value: 0x7f090026
			public const int feedImage1 = 2131296294;
			
			// aapt resource value: 0x7f090028
			public const int feed_menu_item = 2131296296;
			
			// aapt resource value: 0x7f090015
			public const int fragmentContainer = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int imageView1 = 2131296278;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int linearLayout2 = 2131296259;
			
			// aapt resource value: 0x7f090018
			public const int linearLayout3 = 2131296280;
			
			// aapt resource value: 0x7f090020
			public const int list = 2131296288;
			
			// aapt resource value: 0x7f090010
			public const int logIn = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int loginProgress = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int loginQuestion = 2131296274;
			
			// aapt resource value: 0x7f090007
			public const int map = 2131296263;
			
			// aapt resource value: 0x7f090022
			public const int name = 2131296290;
			
			// aapt resource value: 0x7f09000f
			public const int password = 2131296271;
			
			// aapt resource value: 0x7f090029
			public const int people_menu_item = 2131296297;
			
			// aapt resource value: 0x7f090019
			public const int personName = 2131296281;
			
			// aapt resource value: 0x7f090021
			public const int profilePic = 2131296289;
			
			// aapt resource value: 0x7f09002a
			public const int profile_menu_item = 2131296298;
			
			// aapt resource value: 0x7f09000a
			public const int progressBar1 = 2131296266;
			
			// aapt resource value: 0x7f09001f
			public const int refresher = 2131296287;
			
			// aapt resource value: 0x7f09001b
			public const int status = 2131296283;
			
			// aapt resource value: 0x7f090001
			public const int statusMessage = 2131296257;
			
			// aapt resource value: 0x7f090023
			public const int timestamp = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int txtStatusMsg = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int txtUrl = 2131296293;
			
			// aapt resource value: 0x7f09000e
			public const int userName = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int view1 = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditProfile = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmailPropertyListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GoogleMap = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GroupHeaderListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loading_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewPost = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int People = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PeopleList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PeopleListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PhonePropertyListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PostDetails = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PostList = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PostListItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Profile = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PropertyListItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TwitterPropertyListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int UrlPropertyListItem = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int action_settings = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int feed_menu_item = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int people_menu_item = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int profile_menu_item = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int CodeFont = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
