#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("App.Android.Resource", IsApplication=true)]

namespace App.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adUnitId = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int cameraBearing = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTargetLat = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLng = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTilt = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraZoom = 2130771975;
			
			// aapt resource value: 0x7f010014
			public const int delegateClass = 2130771988;
			
			// aapt resource value: 0x7f010012
			public const int headerInAnimation = 2130771986;
			
			// aapt resource value: 0x7f010010
			public const int headerLayout = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int headerOutAnimation = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int headerTransformerClass = 2130771989;
			
			// aapt resource value: 0x7f010002
			public const int mapType = 2130771970;
			
			// aapt resource value: 0x7f010013
			public const int refreshScrollDistance = 2130771987;
			
			// aapt resource value: 0x7f010008
			public const int uiCompass = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiRotateGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiScrollGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiTiltGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomControls = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int useViewLifecycle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int zOrderOnTop = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050014
			public const int ab_background = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int ab_bottom_shadow_1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int ab_bottom_shadow_2 = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int action_bar_title_color = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int blueclick = 2131034122;
			
			// aapt resource value: 0x7f050017
			public const int btn_bg_color = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btn_bg_shadow_color = 2131034136;
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f050019
			public const int common_signin_btn_text_dark = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int common_signin_btn_text_light = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int disabledText = 2131034139;
			
			// aapt resource value: 0x7f05000b
			public const int greyheadertext = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int main_background = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int xam_blue = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int xam_dark_blue = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int xam_gray = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int xam_green = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int xam_light_gray = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int xam_purple = 2131034124;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int activity_horizontal_margin = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int activity_vertical_margin = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int btn_corner_radius = 2131296258;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_shirt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_bg_inactive = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_bg_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_bg_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonimage = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cart = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_disabled_focus_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_disabled_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_focus_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_focus_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_normal_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_normal_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_pressed_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_pressed_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_disabled_focus_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_disabled_focus_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_disabled_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_focus_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_focus_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_normal_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_normal_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_pressed_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_pressed_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int complete = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int configure = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int discrete_shadow = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dummy_avatar = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int empty_basket = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int gallery_next = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int gallery_prev = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_action_basket = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_logo = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_plusone_medium_off_client = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_plusone_small_off_client = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_plusone_standard_off_client = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_plusone_tall_off_client = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Icon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Icon2x = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int login_button = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int loginbox = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int monkey = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Placeholder = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int processing = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ProductImage = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int purple_shirt = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int questionmark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int shirt_image = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int twitter = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int user_default_avatar = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int wrench = 2130837562;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int Divider = 2131099682;
			
			// aapt resource value: 0x7f06000d
			public const int EmailButton = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int HeaderTextView = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int NameTextView = 2131099660;
			
			// aapt resource value: 0x7f060024
			public const int PhoneButton = 2131099684;
			
			// aapt resource value: 0x7f06001a
			public const int PostText = 2131099674;
			
			// aapt resource value: 0x7f060025
			public const int PostTextLabel = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int ProfileList = 2131099687;
			
			// aapt resource value: 0x7f06001d
			public const int SwipeContent = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int UserNameText = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int ValueTextView = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int dialogImage = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int dialogLayout = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int dialogTitle = 2131099667;
			
			// aapt resource value: 0x7f060007
			public const int displayName = 2131099655;
			
			// aapt resource value: 0x7f060020
			public const int distance = 2131099680;
			
			// aapt resource value: 0x7f060028
			public const int feed_menu_item = 2131099688;
			
			// aapt resource value: 0x7f06001b
			public const int fragmentContainer = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int hybrid = 2131099652;
			
			// aapt resource value: 0x7f06001c
			public const int imageView1 = 2131099676;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout2 = 2131099658;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout3 = 2131099678;
			
			// aapt resource value: 0x7f060026
			public const int list = 2131099686;
			
			// aapt resource value: 0x7f060016
			public const int logIn = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int loginProgress = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int loginQuestion = 2131099672;
			
			// aapt resource value: 0x7f060023
			public const int map = 2131099683;
			
			// aapt resource value: 0x7f060000
			public const int none = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int normal = 2131099649;
			
			// aapt resource value: 0x7f060015
			public const int password = 2131099669;
			
			// aapt resource value: 0x7f060029
			public const int people_menu_item = 2131099689;
			
			// aapt resource value: 0x7f06001f
			public const int personName = 2131099679;
			
			// aapt resource value: 0x7f06002a
			public const int profile_menu_item = 2131099690;
			
			// aapt resource value: 0x7f060010
			public const int progressBar1 = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int ptr_progress = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int ptr_text = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int satellite = 2131099650;
			
			// aapt resource value: 0x7f060021
			public const int status = 2131099681;
			
			// aapt resource value: 0x7f060008
			public const int statusMessage = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int terrain = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int userName = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int view1 = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int default_header = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditProfile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EmailPropertyListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GroupHeaderListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loading_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewPost = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int People = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PeopleList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PeopleListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PeopleMap = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PhonePropertyListItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PostDetails = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PostList = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PostListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Profile = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int PropertyListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TwitterPropertyListItem = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int UrlPropertyListItem = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menu = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001b
			public const int ApplicationName = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int Hello = 2131165210;
			
			// aapt resource value: 0x7f07001e
			public const int app_name = 2131165214;
			
			// aapt resource value: 0x7f070015
			public const int auth_client_needs_enabling_title = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int auth_client_needs_installation_title = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int auth_client_needs_update_title = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int auth_client_play_services_err_notification_msg = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int auth_client_requested_by_msg = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int auth_client_using_bad_version_title = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_enable_button = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_enable_text = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_enable_title = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_install_text_phone = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_install_text_tablet = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_install_title = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_invalid_account_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_invalid_account_title = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_network_error_text = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_network_error_title = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_unknown_issue = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unsupported_date_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_unsupported_text = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_unsupported_title = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_update_button = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_update_title = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int common_signin_button_text = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int common_signin_button_text_long = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int pull_to_refresh_pull_label = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int pull_to_refresh_refreshing_label = 2131165213;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int CustomHoloTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int WalkrSubTitleStyle = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int XamActionBarStyle = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int XamActionBarTheme = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int XamActionBarTitleStyle = 2131361796;
			
			// aapt resource value: 0x7f0a0007
			public const int XamButton = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int XamSubtitleText = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int XamTitleText = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adUnitId = 1;
			
			public static int[] MapAttrs = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] PullToRefreshLayout = new int[]
			{
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 4
			public const int PullToRefreshLayout_delegateClass = 4;
			
			// aapt resource value: 2
			public const int PullToRefreshLayout_headerInAnimation = 2;
			
			// aapt resource value: 0
			public const int PullToRefreshLayout_headerLayout = 0;
			
			// aapt resource value: 1
			public const int PullToRefreshLayout_headerOutAnimation = 1;
			
			// aapt resource value: 5
			public const int PullToRefreshLayout_headerTransformerClass = 5;
			
			// aapt resource value: 3
			public const int PullToRefreshLayout_refreshScrollDistance = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
