#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("App.Android.Resource", IsApplication=true)]

namespace App.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int delegateClass = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int headerInAnimation = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int headerLayout = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int headerOutAnimation = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int headerTransformerClass = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int refreshScrollDistance = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int blueclick = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int disabledText = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int greyheadertext = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int login_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int loginbox = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Placeholder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int questionmark = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int CancelButton = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int Divider = 2131034134;
			
			// aapt resource value: 0x7f05000c
			public const int PostDetailsHeader = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int PostLabel = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int PostList = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int PostText = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int PostTextLabel = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int SaveButton = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int StreamLayout = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int UserImageButton = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int UserNameText = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int dialogImage = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int dialogLayout = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int dialogTitle = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout2 = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int logIn = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int loginProgress = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int loginQuestion = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int password = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int ptr_progress = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ptr_text = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int userName = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int default_header = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewPost = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PostDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PostListItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int pull_to_refresh_pull_label = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int pull_to_refresh_refreshing_label = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CustomHoloTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefreshLayout = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int PullToRefreshLayout_delegateClass = 4;
			
			// aapt resource value: 2
			public const int PullToRefreshLayout_headerInAnimation = 2;
			
			// aapt resource value: 0
			public const int PullToRefreshLayout_headerLayout = 0;
			
			// aapt resource value: 1
			public const int PullToRefreshLayout_headerOutAnimation = 1;
			
			// aapt resource value: 5
			public const int PullToRefreshLayout_headerTransformerClass = 5;
			
			// aapt resource value: 3
			public const int PullToRefreshLayout_refreshScrollDistance = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
